<?xml version='1.0' encoding='UTF-8'?><wsdl:definitions xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://casemanagement.webservices.casem.fujitsu.fi/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:ns3="http://schemas.xmlsoap.org/soap/http" xmlns:ns1="http://docs.oasis-open.org/ns/cmis/ws/200908/" name="CMISVersioningServiceService" targetNamespace="http://casemanagement.webservices.casem.fujitsu.fi/">
  <wsdl:import location="https://tiedonhallintapalvelutesti.tiera.fi:9443/casem-cmis-ws/CMISVersioningService?wsdl=VersioningServicePort.wsdl" namespace="http://docs.oasis-open.org/ns/cmis/ws/200908/">
    </wsdl:import>
  <wsdl:binding name="CMISVersioningServiceServiceSoapBinding" type="ns1:VersioningServicePort">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="checkOut">
      <soap:operation soapAction="checkOut" style="document"/>
      <wsdl:input name="checkOut">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="checkOutResponse">
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="CmisException">
        <soap:fault name="CmisException" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="cancelCheckOut">
      <soap:operation soapAction="cancelCheckOut" style="document"/>
      <wsdl:input name="cancelCheckOut">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="cancelCheckOutResponse">
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="CmisException">
        <soap:fault name="CmisException" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="checkIn">
      <soap:operation soapAction="checkIn" style="document"/>
      <wsdl:input name="checkIn">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="checkInResponse">
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="CmisException">
        <soap:fault name="CmisException" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="CMISVersioningServiceService">
    <wsdl:port binding="tns:CMISVersioningServiceServiceSoapBinding" name="CMISVersioningServicePort">
      <soap:address location="https://tiedonhallintapalvelutesti.tiera.fi:9443/casem-cmis-ws/CMISVersioningService"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>