<?xml version='1.0' encoding='UTF-8'?><wsdl:definitions xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://casemanagement.webservices.casem.fujitsu.fi/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:ns3="http://schemas.xmlsoap.org/soap/http" xmlns:ns1="http://docs.oasis-open.org/ns/cmis/ws/200908/" name="CMISDiscoveryServiceService" targetNamespace="http://casemanagement.webservices.casem.fujitsu.fi/">
  <wsdl:import location="https://tiedonhallintapalvelutesti.tiera.fi:9443/casem-cmis-ws/CMISDiscoveryService?wsdl=DiscoveryServicePort.wsdl" namespace="http://docs.oasis-open.org/ns/cmis/ws/200908/">
    </wsdl:import>
  <wsdl:binding name="CMISDiscoveryServiceServiceSoapBinding" type="ns1:DiscoveryServicePort">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="query">
      <soap:operation soapAction="query" style="document"/>
      <wsdl:input name="query">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="queryResponse">
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="CmisException">
        <soap:fault name="CmisException" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="getContentChanges">
      <soap:operation soapAction="getContentChanges" style="document"/>
      <wsdl:input name="getContentChanges">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="getContentChangesResponse">
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="CmisException">
        <soap:fault name="CmisException" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="CMISDiscoveryServiceService">
    <wsdl:port binding="tns:CMISDiscoveryServiceServiceSoapBinding" name="CMISDiscoveryServicePort">
      <soap:address location="https://tiedonhallintapalvelutesti.tiera.fi:9443/casem-cmis-ws/CMISDiscoveryService"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>